name: esp_provisioning_example
description: Demonstrates how to use the esp_provisioning plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  esp_provisioning:
    path: ../
  flutter_bloc: ^8.0.1
  logger: ^1.1.0
  permission_handler: ^10.0.0
  equatable: ^2.0.3
  rxdart: ^0.27.5
  flutter_spinkit: ^5.1.0
  # The following packages is integrated to scan and connect to BLE Device, this package is actively maintained as of Feb,2023.
  flutter_blue_plus: ^1.33.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

enable-experiment:
  - extension-methods